spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/bolsa
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
