FROM node:16-alpine as build

WORKDIR /usr/src/app


COPY ./package*.json ./


RUN npm install --legacy-peer-deps


COPY . .


RUN npm run build --prod


FROM nginx:alpine


COPY --from=build /usr/src/app/dist/zg-invest-table /usr/share/nginx/html


EXPOSE 80

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]
