version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123  
      POSTGRES_DB: bolsa
    ports:
      - "5432:5432"
    volumes:
      - ./bolsa.bkp:/docker-entrypoint-initdb.d/bolsa.bkp
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres: 
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
